config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#index'
  get '/auth/github', as: :github_login
  get '/auth/github/callback', to: "sessions#create"
  delete '/logout', to: "sessions#destroy"
  namespace :authorized do
    get '/profile', to: "profile#show"
    get '/repos', to: "repositories#index"
    get '/activity', to: "activity#index"
    get '/following_activity', to: "following_activity#index"
    get '/organizations', to: "organizations#index"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  validates_presence_of :name, :email, :provider, :uid, :screen_name, :oauth_token, :image_url
  has_many :repos

  def self.find_or_create_by_auth(auth)
    user = User.find_or_create_by(provider: auth['provider'], uid: auth['uid'])

    user.provider = auth['provider']
    user.name = auth['info']['name']
    user.email = auth['info']['email']
    user.uid = auth['uid']
    user.screen_name = auth['info']['nickname']
    user.oauth_token = auth['credentials']['token']
    user.image_url = auth['info']['image']

    user.save
    user
  end

  def self.find_starred_repos(screen_name)
    GithubService.find_starred_repos(screen_name)
  end

  def self.find_followers(screen_name)
    GithubService.find_followers(screen_name)
  end

  def self.find_following(screen_name)
    GithubService.find_following(screen_name)
  end

  def self.find_organizations(screen_name)
    GithubService.find_organizations(screen_name)
  end

  def self.find_repos(screen_name)
    GithubService.find_repos(screen_name)
  end

  def self.find_events(screen_name)
    GithubService.find_events(screen_name)
  end

  def self.find_following_events(screen_name)
    GithubService.find_following_events(screen_name)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/authorized/activity_controller.rb
class Authorized::ActivityController < Authorized::AuthController

  def index
    @commits = User.find_events(current_user.screen_name)
  end

end

app/controllers/authorized/auth_controller.rb
class Authorized::AuthController < ApplicationController
  before_action :require_auth

  def require_auth
    render file: "/public/404" unless current_user
  end
end

app/controllers/authorized/following_activity_controller.rb
class Authorized::FollowingActivityController < Authorized::AuthController

  def index
    @events = User.find_following_events(current_user.screen_name)
  end

end

app/controllers/authorized/organizations_controller.rb
class Authorized::OrganizationsController < Authorized::AuthController

  def index
    @organizations = User.find_organizations(current_user.screen_name)
  end

end

app/controllers/authorized/profile_controller.rb
class Authorized::ProfileController < Authorized::AuthController

  def show
    @user = current_user
    @starred_repos = User.find_starred_repos(current_user.screen_name)
    @followers = User.find_followers(current_user.screen_name)
    @following = User.find_following(current_user.screen_name)
  end

end

app/controllers/authorized/repositories_controller.rb
class Authorized::RepositoriesController < Authorized::AuthController

  def index
    @repos = User.find_repos(current_user.screen_name)
  end

end

app/controllers/sessions_controller.rb
class SessionsController<ApplicationController

  def create
    @user = User.find_or_create_by_auth(request.env['omniauth.auth'])
    if @user
      session[:user_id] = @user.id
      redirect_to authorized_profile_path
    end
  end

  def destroy
    session.clear
    redirect_to root_path
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    
  end

end

app/views/authorized/activity/index.html.erb
<div class="container text-center">

  <h1>Your Recent Commits</h1>

    <table class="table profile-tables">

      <thead>
        <th>Date</th>
        <th align="center">Repo</th>
        <th>Message</th>
      </thead>

      <tbody>
        <% @commits.each do |commit| %>
        <tr>
          <th scope="row"> <%= commit[:date].strftime("%a %b %e %Y ") %> </th>
            <td align="left"> <%= commit[:repo] %> </td>
            <td align="left"> <%= commit[:message] %>  </td>
        </tr>
        <% end %>
      </tbody>

    </table>

    </div>

app/views/authorized/following_activity/index.html.erb
<div class="container text-center">

  <h1>Events from People You Follow</h1>

    <table class="table profile-tables">

      <thead>
        <th>Person</th>
        <th>Date</th>
        <th>Event Type</th>
        <th>Repo</th>
      </thead>

      <tbody>
        <% @events.each do |event| %>
        <tr>
          <th scope="row"><%= event[:user] %></th>
            <td align="left"><%= event[:date].strftime("%a %b %e %Y ") %></td>
            <td align="left"><%= event[:type] %></td>
            <td align="left"><%= event[:repo] %></td>
        </tr>
        <% end %>
      </tbody>

    </table>

    </div>

app/views/authorized/organizations/index.html.erb
<h1 class="text-center">Your Organizations</h1>
<div class="container text-center profile-tables">
  <% @organizations.each do |org| %>
    <h4><%= link_to org[:login], org[:url], target: :_blank %></h4>
  <% end %>
</div>

app/views/authorized/profile/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12 text-center">
      <div class="profile-pic">
        <img src="<%= @user.image_url %>" alt="Profile image">
      </div>
      <div class="profile-name">
        <h1 class="display-3"><%= @user.name %></h1>
      </div>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-lg-12 text-center">
      <div class="tabpanel text-center">

        <ul class="nav nav-pills pills" role="tablist">
          <li class="nav-item">
            <a class="nav-link active" data-toggle="pill" href="#starred-repos" role="pill">Starred Repos</a>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled" data-toggle="pill" href="#followers" role="pill">Followers</a>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled" data-toggle="pill" href="#following" role="pill">Following</a>
          </li>
        </ul>

        <div class="tab-content" id="tabs">
          <div class="tab-pane" id="starred-repos" role="tabpanel">
            <table class="table profile-tables">
              <thead>
                <th>Name</th>
                <th>Owner</th>
                <th>Description</th>
              </thead>

              <tbody>
              <% @starred_repos.each do |repo| %>
                <tr>
                  <th scope="row"><%= link_to repo[:full_name].split('/')[-1], repo[:html_url], target: :_blank %></th>
                  <td align="left"><%= repo[:owner][:login] %></td>
                  <td align="left"><%= repo[:description] %></td>
                  </tr>
              <% end %>
              </tbody>
            </table>

          </div>



          <div class="tab-pane profile-tables" id="followers" role="tabpanel">
           <% @followers.each do |follower| %>
              <h4><%= link_to follower[:login], follower[:html_url], target: :_blank %></h4>
           <% end %>
          </div>

          <div class="tab-pane profile-tables" id="following" role="tabpanel">
            <% @following.each do |following| %>
              <h4><%= link_to following[:login], following[:html_url], target: :_blank %></h4>
            <% end %>
          </div>
        </div>

      </div>
    </div>
  </div>
</div>

app/views/authorized/repositories/index.html.erb
<h1 class="text-center">Your Repositories</h1>
<div class="container text-center profile-tables">
  <table class="table">

      <thead>
        <th>Repo Name</th>
        <th>Description</th>
      </thead>

      <tbody>
        <% @repos.each do |repo| %>
        <tr>
          <th scope="row"><%= link_to repo[:name], repo[:html_url], target: :_blank %></th>
            <td align="left"><%= repo[:description] %></td>
        </tr>
        <% end %>
      </tbody>

    </table>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default navbar-styles">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" id="navbar-text" href="/">YourHub</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" id="navbar-text">Your Stuff<span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", authorized_profile_path %></li>
              <li><%= link_to "Your Repos", authorized_repos_path %></li>
              <li><%= link_to "Your Recent Activity", authorized_activity_path %></li>
              <li><%= link_to "Following Activity", authorized_following_activity_path %></li>
              <li><%= link_to "Organizations", authorized_organizations_path %></li>
            </ul>
          </li>
          <li><%= link_to "Logout", logout_path, method: :delete, id: "navbar-text" %></li>
        <% else %>
          <li><%= link_to "Login with Github", github_login_path, id: "navbar-text" %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Apicurious</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: "layouts/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<div class="container text-center">
  <img src="https://octodex.github.com/images/octobiwan.jpg" alt="Octobiwan Cat">
</div>